name: 'Bike Club - Media'
description: 'Install image and file media types, configuration, and taxonomies.'
type: 'Site'
install:
  # Core modules
  - field
  - file
  - media
  - media_library
  - path
  - responsive_image
  - views
  # Contrib modules
  - crop
  - entity_browser
  - field_group
  - image_widget_crop
  - magnific_popup  
  - views_slideshow
  - views_slideshow_cycle
config:
  import:
    file:
      - views.view.files
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - core.entity_view_mode.media.full
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
    image:
      - image.style.medium
      - image.style.large
      - image.style.thumbnail 
    image_widget_crop: '*'
