name: 'Bike Club - Media'
description: 'Installs image and file media types, configuration, and taxonomies.'
type: 'Site'
install:
  # Core modules
  - field
  - file
  - media
  - media_library
  - path
  - responsive_image
  - views
  # Contrib modules
  - crop
  - entity_browser
  - field_group
  - image_widget_crop
  - magnific_popup 
  - svg_image
  - views_slideshow
  - views_slideshow_cycle
config:
  import:
    file:
      - views.view.files
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - core.entity_view_mode.media.full
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
    image:
      - image.style.medium
      - image.style.large
      - image.style.thumbnail 
    image_widget_crop: '*'
  actions:
    # Assign Drupal permissions for media.
    # Content creator/ride_leader may delete/update own media.
    # Editor/rides_coordinator/site_admin may delete/update any media.
    user.role.anonymous:
      grantPermissions:
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'change own username'
        - 'delete own files'
        - 'view media'
    user.role.content_creator:
      grantPermissions:
        - 'access media overview'  
        - 'create media'
        - 'delete media'
        - 'update media'
        - 'view own unpublished media'
    user.role.editor:
      grantPermissions:
        - 'access media overview'
        - 'create media'
        - 'delete any media'
        - 'update any media'
        - 'view own unpublished media'
    user.role.rides_coordinator:
      grantPermissions:
        - 'access media overview'
        - 'create media'
        - 'delete any media'
        - 'update any media'
        - 'view own unpublished media'
    user.role.ride_leader:
      grantPermissions:
        - 'create media'
        - 'delete media'
        - 'update media'
        - 'view own unpublished media'
    user.role.site_admin:
      grantPermissions:
        - 'access media overview'
        - 'create media'
        - 'delete any media'
        - 'update any media'
        - 'view own unpublished media'